import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation files
const translations = {
  en: {
    common: {
      scanWebsite: "Scan Website",
      scanning: "Scanning...",
      startScanning: "Start Scanning Now",
      clearResults: "Clear Results",
      downloadPdf: "Download PDF",
      emailReport: "Email Report",
      accessibilityScore: "Accessibility Score",
      scanned: "Scanned",
      outOf: "out of",
      issuesFound: "issues found",
      issue: "issue",
      language: "Language",
      errorScanFailed: "Failed to scan website. Please try again.",
      errorGeneric: "An error occurred. Please try again.",
      errorEnterUrl: "Please enter a URL"
    },
    home: {
      title: "Make Your Website Accessible to Everyone",
      subtitle: "Get instant accessibility insights with our advanced AI-powered scanner. Ensure your website meets WCAG 2.1 standards and create an inclusive digital experience for all users.",
      enterUrl: "Enter website URL",
      urlPlaceholder: "https://example.com",
      wcagIssues: "WCAG Accessibility Issues",
      uxAuditResults: "UX Audit Results",
      severityHigh: "High",
      severityMedium: "Medium",
      severityLow: "Low",
      priority: "Priority",
      categoryMobile: "Mobile",
      categoryNavigation: "Navigation",
      categoryEngagement: "Engagement",
      categoryForms: "Forms",
      categoryContent: "Content",
      categorySEO: "SEO",
      categoryPerformance: "Performance",
      recommendation: "Recommendation:",
      impact: "Impact:",
      violationImpactCritical: "Critical",
      violationImpactSerious: "Serious",
      violationImpactModerate: "Moderate",
      violationImpactMinor: "Minor",
      violationCode: "Code",
      violationHowToFix: "How to fix",
      violationFixDescription: "Review the element and ensure it follows accessibility best practices. Check WCAG guidelines for specific requirements.",
      // UX Audit Issues
      uxIssueViewportTitle: "Missing Viewport Meta Tag",
      uxIssueViewportDesc: "The page lacks a viewport meta tag, which may cause poor mobile user experience.",
      uxIssueViewportRec: "Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> to the head section.",
      uxIssueViewportImpact: "Users on mobile devices may experience zoomed-out or improperly scaled content.",
      uxIssueNavigationTitle: "Unclear Navigation Structure",
      uxIssueNavigationDesc: "No semantic navigation or header elements found. Users may struggle to find their way around.",
      uxIssueNavigationRec: "Use <nav> or <header> elements to clearly define navigation and page structure.",
      uxIssueNavigationImpact: "Users may experience confusion when navigating the site.",
      uxIssueCTATitle: "Limited Call-to-Action Elements",
      uxIssueCTADesc: "Few interactive elements (buttons/links) found. Users may have limited engagement options.",
      uxIssueCTARec: "Ensure important actions are clearly visible as buttons or prominent links.",
      uxIssueCTAImpact: "Users may miss important actions or next steps.",
      uxIssueFormsTitle: "Forms May Lack Clear Labels",
      uxIssueFormsDesc: "Some form inputs appear to be missing labels, which can confuse users.",
      uxIssueFormsRec: "Ensure all form inputs have associated <label> elements or aria-labels for clarity.",
      uxIssueFormsImpact: "Users may struggle to understand what information to enter in form fields.",
      uxIssueContentTitle: "Unclear Content Hierarchy",
      uxIssueContentDesc: "No main heading (H1) found. Content structure may be unclear to users.",
      uxIssueContentRec: "Use proper heading hierarchy (H1, H2, H3) to organize content logically.",
      uxIssueContentImpact: "Users may struggle to understand the page's main purpose and content flow.",
      uxIssueImageTitle: "Images May Lack Alt Text",
      uxIssueImageDesc: "Some images appear to be missing descriptive alt text, affecting accessibility.",
      uxIssueImageRec: "Add descriptive alt text to all images using the alt attribute.",
      uxIssueImageImpact: "Users with screen readers won't understand image content.",
      uxIssueMetaTitle: "Missing Meta Description",
      uxIssueMetaDesc: "The page lacks a meta description tag, which affects SEO and search result previews.",
      uxIssueMetaRec: "Add a <meta name=\"description\"> tag with a concise page description.",
      uxIssueMetaImpact: "Search engines and users won't see a preview description in search results.",
      websitesScanned: "Websites Scanned",
      accuracyRate: "Accuracy Rate",
      issuesFixed: "Issues Fixed",
      compliance: "Compliance"
    },
    about: {
      title: "Making the Web Accessible, One Scan at a Time",
      subtitle: "We're on a mission to make digital accessibility testing as simple as checking your email. Because everyone deserves to access the web, regardless of their abilities.",
      startFirstScan: "Start Your First Scan",
      ourStory: "Our Story",
      storyParagraph1: "It started with a simple observation: while working on web projects, we noticed that accessibility testing was always an afterthought—if it happened at all.",
      storyParagraph2: "We saw developers struggling with complex, expensive tools that took forever to run. We saw designers creating beautiful interfaces that worked great for some users but completely failed others. And most importantly, we saw millions of people being excluded from the digital world simply because their needs weren't considered.",
      storyParagraph3: "So we built ScanWeb—a tool that makes accessibility testing as simple as checking your email. No complex setup, no expensive licenses, no waiting around for results. Just enter a URL, click scan, and get actionable insights in seconds.",
      theNumbers: "The Numbers Don't Lie",
      stat1: "People with disabilities worldwide",
      stat2: "Of users with disabilities leave sites due to poor accessibility",
      stat3: "Of the global population has a disability",
      stat4: "Higher conversion rates for accessible websites",
      whyChoose: "Why Choose ScanWeb?",
      feature1Title: "Lightning Fast Scans",
      feature1Desc: "Get comprehensive accessibility reports in under 30 seconds. No more waiting around for slow, outdated tools.",
      feature2Title: "Developer-Friendly",
      feature2Desc: "Built by developers, for developers. Integrate seamlessly into your workflow with our API and CI/CD tools.",
      feature3Title: "Design Integration",
      feature3Desc: "Perfect for designers who want to ensure their creations work for everyone, not just the majority.",
      feature4Title: "Expert Guidance",
      feature4Desc: "Don't just find problems—learn how to fix them with our detailed guides and actionable recommendations.",
      ourValues: "Our Values",
      value1Title: "Inclusion First",
      value1Desc: "We believe digital products should work for everyone, regardless of ability. Every decision we make is guided by this principle.",
      value2Title: "Simplicity Matters",
      value2Desc: "Accessibility testing shouldn't be complicated. We've made it as simple as entering a URL and clicking scan.",
      value3Title: "Continuous Innovation",
      value3Desc: "The web evolves constantly, and so do we. We're always improving our tools to catch the latest accessibility issues.",
      readyToMake: "Ready to Make Your Website Accessible?",
      joinThousands: "Join thousands of developers and designers who are already using ScanWeb to create more inclusive digital experiences."
    },
    nav: {
      home: "Home",
      about: "About",
      pricing: "Pricing",
      resources: "Resources",
      apiDocs: "API Docs",
      allTools: "All Tools"
    },
    pricing: {
      title: "Simple, Transparent Pricing",
      subtitle: "Choose the plan that fits your needs. Start free, upgrade anytime.",
      planFree: "Free",
      planPro: "Pro",
      planEnterprise: "Enterprise",
      planFreeDesc: "Perfect for getting started with accessibility testing",
      planProDesc: "For professionals who need comprehensive accessibility testing",
      planEnterpriseDesc: "For teams and organizations with advanced needs",
      planForever: "forever",
      planPerMonth: "per month",
      planCustom: "Custom",
      planCustomPricing: "pricing",
      featureUnlimitedScans: "Unlimited scans",
      feature10Scans: "Up to 10 scans per month",
      featureBasicReport: "Basic accessibility report",
      featureAdvancedReport: "Advanced accessibility reports",
      featureWCAGAA: "WCAG 2.1 AA compliance check",
      featureWCAGAAA: "WCAG 2.1 AAA compliance check",
      featureEmailSupport: "Email support",
      featurePrioritySupport: "Priority support",
      featureCommunity: "Community resources",
      featurePDFExport: "PDF and CSV export",
      featureEmailReports: "Email reports",
      featureAPIAccess: "API access",
      featureCustomIntegrations: "Custom integrations",
      featureEverythingPro: "Everything in Pro",
      featureTeamCollab: "Team collaboration tools",
      featureAnalytics: "Advanced analytics dashboard",
      featureCustomFrameworks: "Custom compliance frameworks",
      featureAccountManager: "Dedicated account manager",
      featureSLA: "SLA guarantee",
      featureOnPremise: "On-premise deployment",
      featureTraining: "Custom training sessions",
      buttonStartFree: "Start Free Trial",
      buttonStartPro: "Start Pro Trial",
      buttonContactSales: "Contact Sales",
      featureFast: "Lightning Fast",
      featureFastDesc: "Get results in under 30 seconds",
      featureSecure: "Secure & Private",
      featureSecureDesc: "Your data is encrypted and never shared",
      featureTeam: "Team Collaboration",
      featureTeamDesc: "Share reports and work together",
      featureSupport: "Expert Support",
      featureSupportDesc: "Get help when you need it",
      mostPopular: "Most Popular"
    },
    resources: {
      title: "Accessibility Resources & Learning",
      subtitle: "Everything you need to master web accessibility",
      categoryAll: "All",
      categoryBeginner: "Beginner",
      categoryAdvanced: "Advanced",
      categoryDesign: "Design",
      categoryTesting: "Testing",
      categoryDevelopment: "Development",
      article1Title: "10 Common Accessibility Issues and How to Fix Them",
      article1Desc: "Learn about the most frequent accessibility problems found on websites and practical solutions to resolve them.",
      article2Title: "WCAG 2.1 Compliance Guide: Complete Web Accessibility Standards",
      article2Desc: "Master the Web Content Accessibility Guidelines (WCAG) 2.1 to create inclusive, accessible websites that comply with international standards.",
      article3Title: "Color Contrast Accessibility: Complete Guide for Web Designers",
      article3Desc: "Master color contrast requirements to create accessible, inclusive designs that meet WCAG standards and provide excellent user experience.",
      article4Title: "Screen Reader Optimization: Complete Accessibility Guide",
      article4Desc: "Learn how to optimize your website for screen readers and assistive technologies. Create inclusive experiences that work seamlessly with NVDA, JAWS, VoiceOver.",
      article5Title: "Keyboard Navigation Accessibility: Complete Implementation Guide",
      article5Desc: "Master keyboard navigation patterns and focus management to create truly accessible web experiences for users who rely on keyboard-only interaction.",
      article6Title: "Mobile Accessibility: Complete Best Practices Guide",
      article6Desc: "Master mobile accessibility to create inclusive experiences on smartphones and tablets. Learn essential techniques for touch interfaces and responsive design.",
      article7Title: "Building Accessible React Components",
      article7Desc: "Best practices for creating accessible React components that work with screen readers and keyboard navigation.",
      minRead: "min read",
      comingSoon: "Coming Soon",
      articlesAndGuides: "Articles & Guides",
      article: "article",
      articles: "articles",
      inCategory: "in",
      readArticle: "Read Article →",
      recommendedTools: "Recommended Tools",
      toolWebAIM: "WebAIM Contrast Checker",
      toolWebAIMDesc: "Online tool for checking color contrast ratios",
      toolColorOracle: "Color Oracle",
      toolColorOracleDesc: "Desktop application for color blindness simulation",
      toolStark: "Stark Plugin",
      toolStarkDesc: "Design tool plugin for accessibility testing",
      toolFeatureRealTime: "Real-time contrast calculation",
      toolFeatureWCAGCheck: "WCAG compliance checking",
      toolFeatureSimulation: "Color blindness simulation",
      toolFeaturePreview: "Real-time preview",
      toolFeatureMultiple: "Multiple color blindness types",
      toolFeatureCrossPlatform: "Cross-platform support",
      toolFeatureIntegration: "Figma/Sketch integration",
      toolFeatureScanning: "Contrast checking",
      visitTool: "Visit Tool",
      stayUpdated: "Stay Updated",
      stayUpdatedDesc: "Get the latest accessibility tips, guides, and industry news delivered to your inbox.",
      subscribeToNewsletter: "Subscribe to Newsletter"
    },
    apiDocs: {
      title: "API Documentation",
      subtitle: "Integrate accessibility scanning into your applications with our powerful REST API.",
      quickStart: "Quick Start",
      quickStartDesc: "Get started with our API in minutes. All you need is an API key and a URL to scan.",
      replaceApiKey: "Replace YOUR_API_KEY with your actual API key",
      copy: "Copy",
      testApi: "Test the API",
      testApiDesc: "Try our API with a real URL to see how it works.",
      websiteUrl: "Website URL",
      success: "Success!",
      error: "Error",
      apiEndpoints: "API Endpoints",
      showDetails: "Show Details",
      hideDetails: "Hide Details",
      parameters: "Parameters",
      required: "Required",
      codeExamples: "Code Examples",
      authentication: "Authentication",
      authDesc: "All API requests require authentication using an API key. Include your API key in the Authorization header.",
      getApiKey: "Get your API key from the dashboard after signing up for a Pro or Enterprise plan.",
      copiedToClipboard: "Copied to clipboard!",
      endpointScanDesc: "Scan a website for accessibility issues",
      endpointBatchDesc: "Scan multiple URLs in a single request",
      paramUrl: "The URL to scan",
      paramDepth: "Scan depth (1-3, default: 1)",
      paramInclude: "Comma-separated list of issue types to include",
      paramUrls: "Array of URLs to scan",
      paramOptions: "Scan options for all URLs"
    },
    tools: {
      title: "Accessibility Testing Tools",
      subtitle: "Powerful tools to test and improve your website's accessibility",
      toolContrast: "Color Contrast Checker",
      toolContrastDesc: "Test color combinations for WCAG accessibility compliance. Input hex codes and get instant contrast ratio results.",
      toolAltText: "Alt Text Analyzer",
      toolAltTextDesc: "Scan any webpage to find images missing alt text attributes. Perfect for quick accessibility audits.",
      toolKeyboard: "Keyboard Navigator",
      toolKeyboardDesc: "Test your website's keyboard navigation and focus management to ensure it works perfectly without a mouse.",
      toolPerformance: "Performance Audit",
      toolPerformanceDesc: "Analyze how accessibility features impact your website's performance and optimize accordingly.",
      toolScreenReader: "Screen Reader Simulator",
      toolScreenReaderDesc: "Experience your website as screen reader users do. Test with NVDA, JAWS, and VoiceOver compatibility.",
      statusAvailable: "Available",
      featureWCAG: "WCAG AA/AAA compliance",
      featureLivePreview: "Live preview",
      featureColorGen: "Random color generator",
      featureDetailedReport: "Detailed compliance report",
      featureBulkScan: "Bulk image scanning",
      featureMissingDetection: "Missing alt text detection",
      featureSuggestions: "Improvement suggestions",
      featureExport: "Export results",
      needAdvanced: "Need More Advanced Features?",
      needAdvancedDesc: "Upgrade to Pro for unlimited scans, advanced reporting, and priority support.",
      viewPricing: "View Pricing",
      viewAPI: "View API Docs"
    },
    keyboardNavigator: {
      title: "Keyboard Navigator",
      subtitle: "Test and improve keyboard navigation on your website. Ensure all interactive elements are accessible via keyboard, making your site usable for everyone regardless of their input method.",
      testTitle: "Test Keyboard Navigation",
      testButton: "Test navigation",
      testing: "Testing...",
      whatWeTest: "What we test:",
      whatWeTestDesc: "Tab order, focus management, keyboard shortcuts, ARIA labels, focus indicators, and skip links.",
      testingInProgress: "Testing in Progress...",
      keyboardNavigationIssues: "Keyboard Navigation Issues",
      excellent: "Excellent! No keyboard navigation issues found.",
      excellentDesc: "All interactive elements are properly accessible via keyboard.",
      bestPracticesTitle: "Keyboard Navigation Best Practices",
      essentialRequirements: "Essential Requirements",
      advancedFeatures: "Advanced Features",
      needMoreTools: "Need More Accessibility Tools?",
      needMoreToolsDesc: "Explore our full suite of accessibility testing tools.",
      viewAllTools: "View All Tools",
      essentialItem1: "Test Tab key navigation through all interactive elements",
      essentialItem2: "Verify logical tab order matches visual layout",
      essentialItem3: "Ensure focus indicators are clearly visible",
      essentialItem4: "Check that Escape key closes all modals and dropdowns",
      essentialItem5: "Test skip links bypass repetitive navigation",
      essentialItem6: "Verify arrow keys work in custom components",
      essentialItem7: "Test keyboard shortcuts don't conflict with browser defaults",
      advancedItem1: "Test custom keyboard shortcuts (Ctrl+S, Alt+N, etc.)",
      advancedItem2: "Verify arrow key navigation in dropdowns and menus",
      advancedItem3: "Test focus trapping in modal dialogs",
      advancedItem4: "Check focus restoration after closing modals",
      advancedItem5: "Test keyboard navigation in single-page applications",
      advancedItem6: "Verify focus management during dynamic content updates",
      advancedItem7: "Test keyboard navigation with screen readers",
      issuesFound: "Issues Found",
      navigationScore: "Navigation Score"
    },
    performanceAudit: {
      title: "Performance Audit",
      subtitle: "Analyze your website's performance and get actionable insights to improve loading speed and user experience. Create lightning-fast websites that users love.",
      auditTitle: "Audit Website Performance",
      startAudit: "Start audit",
      auditing: "Auditing...",
      whatWeAnalyze: "What we analyze:",
      whatWeAnalyzeDesc: "Core Web Vitals, loading performance, resource optimization, caching strategies, and accessibility impact on performance.",
      performanceScore: "Performance Score",
      excellent: "Excellent performance!",
      good: "Good performance with room for improvement",
      needsImprovement: "Performance needs significant improvement",
      coreWebVitals: "Core Web Vitals",
      performanceIssues: "Performance Issues",
      quickRecommendations: "Quick Recommendations",
      bestPracticesTitle: "Performance Best Practices",
      coreOptimizations: "Core Optimizations",
      advancedTechniques: "Advanced Techniques",
      needMoreTools: "Need More Performance Tools?",
      needMoreToolsDesc: "Explore our full suite of performance and accessibility testing tools.",
      coreItem1: "Test page load speed and Core Web Vitals",
      coreItem2: "Analyze image optimization and format usage",
      coreItem3: "Check JavaScript bundle size and loading performance",
      coreItem4: "Verify CSS optimization and critical path",
      coreItem5: "Test mobile performance and responsive loading",
      coreItem6: "Check server response times and caching headers",
      coreItem7: "Analyze third-party script impact on performance",
      advancedItem1: "Test code splitting and dynamic imports",
      advancedItem2: "Analyze service worker implementation and caching",
      advancedItem3: "Check critical CSS extraction and inlining",
      advancedItem4: "Test resource hints (preload, prefetch, preconnect)",
      advancedItem5: "Verify HTTP/2 and HTTP/3 optimization",
      advancedItem6: "Test progressive web app performance features",
      advancedItem7: "Analyze performance budgets and monitoring",
      performanceScore: "Performance Score",
      excellentPerformance: "Excellent performance!",
      goodPerformance: "Good performance with room for improvement",
      needsImprovement: "Performance needs significant improvement"
    },
    screenReaderSimulator: {
      title: "Screen Reader Simulator",
      subtitle: "Experience your website as screen reader users do. Test accessibility and improve the experience for all users, ensuring your content is truly inclusive and accessible.",
      simulateTitle: "Simulate Screen Reader Experience",
      startSimulation: "Start simulation",
      simulating: "Simulating...",
      whatWeSimulate: "What we simulate:",
      whatWeSimulateDesc: "Screen reader navigation, ARIA announcements, heading structure, form labels, and landmark identification.",
      accessibilityScore: "Accessibility Score",
      accessibleElements: "Accessible Elements",
      issuesFound: "Issues Found",
      totalElements: "Total Elements",
      screenReaderOutput: "Screen Reader Output",
      issuesFoundTab: "Issues Found",
      recommendationsTab: "Recommendations",
      accessibilityIssues: "Accessibility Issues",
      bestPracticesTitle: "Screen Reader Best Practices",
      essentialRequirements: "Essential Requirements",
      advancedFeatures: "Advanced Features",
      needMoreTools: "Need More Accessibility Tools?",
      needMoreToolsDesc: "Explore our full suite of accessibility testing and simulation tools.",
      essentialItem1: "Test how screen readers announce page content",
      essentialItem2: "Verify alt text is descriptive and meaningful",
      essentialItem3: "Check heading hierarchy and document structure",
      essentialItem4: "Test form labels and error announcements",
      essentialItem5: "Verify ARIA labels and descriptions are announced",
      essentialItem6: "Test landmark navigation and page regions",
      essentialItem7: "Check live regions for dynamic content updates",
      advancedItem1: "Test live regions for real-time content updates",
      advancedItem2: "Verify focus management in modal dialogs",
      advancedItem3: "Test skip links and landmark navigation",
      advancedItem4: "Check descriptive link text and context",
      advancedItem5: "Test with multiple screen reader software",
      advancedItem6: "Verify ARIA announcements and state changes",
      advancedItem7: "Test complex interactions and custom components",
      accessibilityScore: "Accessibility Score",
      accessibleElements: "Accessible Elements",
      totalElements: "Total Elements"
    },
    altTextAnalyzer: {
      title: "Alt Text Analyzer",
      subtitle: "Analyze and improve alt text for images on your website to ensure accessibility for screen readers. Make your visual content accessible to everyone.",
      analyzeTitle: "Analyze Website Images",
      analyzeDesc: "Enter a website URL to analyze all images for proper alt text implementation.",
      analyzeImages: "Analyze images",
      analyzing: "Analyzing...",
      websiteUrl: "Website URL",
      totalImages: "Total Images",
      withAltText: "With Alt Text",
      missingAlt: "Missing Alt",
      emptyAlt: "Empty Alt",
      issuesFound: "Issues Found",
      bestPracticesTitle: "Alt Text Best Practices",
      dos: "Do's",
      donts: "Don'ts",
      do1: "Test alt text with screen readers",
      do1Desc: "Verify how alt text sounds when read aloud by assistive technology",
      do2: "Check for missing alt attributes",
      do2Desc: "Scan all images to ensure they have proper alt text or empty alt attributes",
      do3: "Verify decorative images have alt=''",
      do3Desc: "Decorative images should have empty alt text to be skipped by screen readers",
      do4: "Test alt text length and clarity",
      do4Desc: "Ensure alt text is concise but descriptive enough to convey meaning",
      dont1: "Ignore images without alt attributes",
      dont1Desc: "Missing alt text makes images completely inaccessible to screen reader users",
      dont2: "Use placeholder or generic alt text",
      dont2Desc: "Text like 'image' or 'photo' provides no meaningful information",
      dont3: "Skip testing with actual screen readers",
      dont3Desc: "Always test how alt text sounds when read by assistive technology",
      dont4: "Forget to test different image types",
      dont4Desc: "Test decorative, informative, and functional images differently"
    },
    colorContrastChecker: {
      title: "Color Contrast Checker",
      subtitle: "Test color combinations to ensure they meet WCAG accessibility standards.",
      chooseColors: "Choose Your Colors",
      foregroundColor: "Foreground Color",
      backgroundColor: "Background Color",
      randomizeColors: "Randomize Colors",
      preview: "Preview",
      sampleText: "Sample Text",
      previewDescription: "This is how your text will look with these colors.",
      contrastAnalysis: "Contrast Analysis",
      contrastRatio: "Contrast Ratio",
      wcagAA: "WCAG AA",
      wcagAAA: "WCAG AAA",
      wcagAALarge: "WCAG AA Large",
      pass: "PASS",
      fail: "FAIL",
      normalText: "Normal Text",
      largeText: "Large Text"
    },
    index: {
      statsScanned: "Websites Scanned",
      statsAccuracy: "Accuracy Rate",
      statsFixed: "Issues Fixed",
      statsCompliance: "Compliance",
      whyChoose: "Why Choose Our Accessibility Scanner?",
      featureAnalysis: "Comprehensive Analysis",
      featureAnalysisDesc: "Advanced AI-powered scanning detects 50+ accessibility issues including color contrast, alt text, keyboard navigation, ARIA labels, and screen reader compatibility with 99.9% accuracy.",
      featureFast: "Lightning Fast Results",
      featureFastDesc: "Get detailed accessibility reports in under 30 seconds with actionable recommendations, code snippets, and priority-based issue categorization for immediate implementation.",
      featureWCAG: "WCAG 2.1 AA Compliance",
      featureWCAGDesc: "Ensures your website meets international accessibility standards (WCAG 2.1 AA) and legal requirements including ADA, Section 508, and EN 301 549 compliance.",
      featureReports: "Professional Reports",
      featureReportsDesc: "Generate comprehensive PDF reports with executive summaries, detailed findings, remediation guides, and progress tracking for stakeholder presentations and compliance documentation.",
      featureSecurity: "Enterprise Security",
      featureSecurityDesc: "Bank-level security with SOC 2 compliance, encrypted data transmission, and privacy-first approach. Your website data is never stored or shared with third parties.",
      featureExpert: "Expert Support",
      featureExpertDesc: "24/7 technical support from accessibility experts, integration assistance, custom scanning rules, and ongoing consultation to ensure your digital accessibility success.",
      tooltipClear: "Clear all scan results and start over",
      ariaUrlLabel: "Website URL to scan for accessibility issues",
      trustedBy: "Trusted by leading organizations worldwide",
      orgFortune500: "Fortune 500 Companies",
      orgGovernment: "Government Agencies",
      orgEducational: "Educational Institutions",
      orgHealthcare: "Healthcare Organizations",
      orgEcommerce: "E-commerce Platforms",
      orgFinancial: "Financial Services",
      technicalSpecs: "Technical Specifications",
      specScanningTech: "Scanning Technology",
      specCompliance: "Compliance Standards",
      specIntegration: "Integration Options",
      detailAIAnalysis: "AI-Powered Analysis",
      detailRealTime: "Real-time Processing",
      detail50Checks: "50+ Check Types",
      detailCustomRules: "Custom Rules Engine",
      detailWCAG: "WCAG 2.1 AA/AAA",
      detailADA: "ADA Compliance",
      detailSection508: "Section 508",
      detailEN301549: "EN 301 549",
      detailRESTAPI: "REST API",
      detailWebhook: "Webhook Support",
      detailCICD: "CI/CD Integration",
      detailBrowserExt: "Browser Extension",
      detailedReportsTitle: "Detailed Reports with Actionable Recommendations",
      detailedReportsDesc: "Our advanced scanner checks your website against WCAG guidelines and provides detailed reports with actionable recommendations.",
      reportWCAGTitle: "WCAG Compliance",
      reportWCAGDesc: "Comprehensive testing against Web Content Accessibility Guidelines 2.1 AA standards.",
      reportDetailedTitle: "Detailed Reports",
      reportDetailedDesc: "Get specific recommendations for each accessibility issue found on your website.",
      reportExportTitle: "Export & Share",
      reportExportDesc: "Download PDF reports or email results to your team for collaborative improvements."
    }
  },
  ru: {
    common: {
      scanWebsite: "Проверить сайт",
      scanning: "Анализируем ваш сайт...",
      startScanning: "Начать проверку",
      clearResults: "Очистить результаты",
      downloadPdf: "Скачать PDF-отчёт",
      emailReport: "Отправить отчёт на email",
      accessibilityScore: "Оценка доступности сайта",
      scanned: "Проверен сайт",
      outOf: "из",
      issuesFound: "найдено проблем",
      issue: "проблема",
      language: "Язык",
      errorScanFailed: "Не удалось проверить сайт. Пожалуйста, попробуйте снова.",
      errorGeneric: "Произошла ошибка. Пожалуйста, попробуйте снова.",
      errorEnterUrl: "Пожалуйста, введите URL"
    },
    home: {
      title: "Делаем веб доступным, одно сканирование за раз",
      subtitle: "Наша миссия — сделать тестирование цифровой доступности таким же простым, как проверка электронной почты. Потому что каждый заслуживает доступа к веб-пространству, независимо от своих способностей.",
      enterUrl: "Введите URL сайта",
      urlPlaceholder: "https://example.com",
      wcagIssues: "Нарушения доступности WCAG",
      uxAuditResults: "Результаты UX-аудита сайта",
      severityHigh: "Высокий",
      severityMedium: "Средний",
      severityLow: "Низкий",
      priority: "Приоритет",
      categoryMobile: "Мобильный",
      categoryNavigation: "Навигация",
      categoryEngagement: "Вовлечение",
      categoryForms: "Формы",
      categoryContent: "Контент",
      categorySEO: "SEO",
      categoryPerformance: "Производительность",
      recommendation: "Рекомендация:",
      impact: "Влияние:",
      violationImpactCritical: "Критично",
      violationImpactSerious: "Серьёзно",
      violationImpactModerate: "Умеренно",
      violationImpactMinor: "Незначительно",
      violationCode: "Код",
      violationHowToFix: "Как исправить",
      violationFixDescription: "Проверьте элемент и убедитесь, что он следует лучшим практикам доступности. Проверьте руководящие принципы WCAG для конкретных требований.",
      // UX Audit Issues - Improved UX Writing
      uxIssueViewportTitle: "Проблема с отображением на мобильных устройствах",
      uxIssueViewportDesc: "Ваш сайт может некорректно отображаться на телефонах и планшетах. Без правильных настроек viewport контент будет слишком мелким или неудобным для чтения.",
      uxIssueViewportRec: "Добавьте эту строку в секцию <head> вашей страницы: <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
      uxIssueViewportImpact: "Посетители с мобильных устройств увидят ваш сайт в неудобном масштабе и могут покинуть страницу.",
      uxIssueNavigationTitle: "Посетителям трудно найти нужное",
      uxIssueNavigationDesc: "На вашем сайте отсутствует чёткая структура навигации. Люди могут потеряться и не найти важные разделы или действия.",
      uxIssueNavigationRec: "Добавьте элементы <nav> или <header>, чтобы помочь пользователям ориентироваться на сайте и находить то, что им нужно.",
      uxIssueNavigationImpact: "Посетители могут не найти нужную информацию и покинуть сайт, что снизит конверсию.",
      uxIssueCTATitle: "Неочевидные действия на странице",
      uxIssueCTADesc: "На странице мало заметных кнопок и ссылок для действий. Посетители могут не понять, что делать дальше.",
      uxIssueCTARec: "Сделайте важные действия более заметными: используйте кнопки вместо обычных ссылок и размещайте их в видимых местах.",
      uxIssueCTAImpact: "Посетители могут пропустить важные действия (оформление заказа, подписку, покупку), что снизит конверсию.",
      uxIssueFormsTitle: "Непонятные поля в формах",
      uxIssueFormsDesc: "Некоторые поля в формах не имеют подписей или описаний. Посетители могут не понять, какую информацию нужно ввести.",
      uxIssueFormsRec: "Добавьте подписи к каждому полю формы. Используйте элемент <label> или атрибут aria-label, чтобы пользователи понимали, что вводить.",
      uxIssueFormsImpact: "Пользователи могут заполнить форму неправильно или вообще отказаться от её заполнения из-за непонимания.",
      uxIssueContentTitle: "Неочевидная структура контента",
      uxIssueContentDesc: "На странице отсутствует главный заголовок (H1). Посетителям может быть непонятно, о чём эта страница и что здесь самое важное.",
      uxIssueContentRec: "Используйте один главный заголовок H1 для описания темы страницы, затем заголовки H2 и H3 для организации остального контента.",
      uxIssueContentImpact: "Посетители могут не понять основное назначение страницы и быстро покинуть её.",
      uxIssueImageTitle: "Изображения без описаний",
      uxIssueImageDesc: "Некоторые изображения на странице не имеют текстового описания. Это мешает людям с нарушениями зрения понять содержимое.",
      uxIssueImageRec: "Добавьте описание к каждому изображению через атрибут alt. Опишите, что изображено, чтобы все посетители могли понять контекст.",
      uxIssueImageImpact: "Пользователи программ чтения с экрана не узнают, что показано на изображениях, что ухудшает доступность сайта.",
      uxIssueMetaTitle: "Страница не отображается в поиске",
      uxIssueMetaDesc: "В результатах поиска Google и других систем ваша страница может отображаться без описания или с автоматически сгенерированным текстом, что снижает привлекательность.",
      uxIssueMetaRec: "Добавьте тег <meta name=\"description\"> с кратким (150-160 символов) и привлекательным описанием страницы.",
      uxIssueMetaImpact: "Ваша страница будет выглядеть менее привлекательно в поиске, что снизит вероятность кликов и переходов на сайт.",
      websitesScanned: "Сайтов проверено",
      accuracyRate: "Точность анализа",
      issuesFixed: "Проблем исправлено",
      compliance: "Соответствие WCAG"
    },
    about: {
      title: "Проверка доступности сайта: делаем интернет доступным для каждого",
      subtitle: "Простая и быстрая проверка доступности веб-сайтов. Мы поможем вам улучшить доступность сайта, соответствие стандартам WCAG 2.1 и создать комфортный пользовательский опыт для всех посетителей, включая людей с ограниченными возможностями.",
      startFirstScan: "Запустить проверку доступности",
      ourStory: "О нашей компании",
      storyParagraph1: "Всё началось с простого наблюдения: работая над веб-проектами, мы заметили, что тестирование доступности всегда было делом второстепенным — если оно вообще проводилось.",
      storyParagraph2: "Мы видели, как разработчики борются со сложными и дорогими инструментами, которые работали очень долго. Мы видели дизайнеров, создающих красивые интерфейсы, которые отлично работали для одних пользователей, но полностью не работали для других. И самое главное, мы видели миллионы людей, исключённых из цифрового мира просто потому, что их потребности не учитывались.",
      storyParagraph3: "Поэтому мы создали ScanWeb — инструмент, который делает проверку доступности такой же простой, как проверка электронной почты. Никаких сложных настроек, дорогих лицензий или долгих ожиданий результатов. Просто введите URL, нажмите «проверить» и получите полезные рекомендации за секунды.",
      theNumbers: "Статистика доступности сайтов",
      stat1: "Человек с ограниченными возможностями в мире",
      stat2: "Пользователей с ограниченными возможностями покидают сайты из-за плохой доступности",
      stat3: "Населения планеты имеют ограниченные возможности",
      stat4: "Выше конверсия у доступных веб-сайтов",
      whyChoose: "Преимущества проверки доступности на ScanWeb",
      feature1Title: "Мгновенная проверка",
      feature1Desc: "Получите подробный отчёт о доступности менее чем за 30 секунд. Больше не нужно ждать результатов от медленных устаревших инструментов.",
      feature2Title: "Для разработчиков",
      feature2Desc: "Создано разработчиками для разработчиков. Легко интегрируйте в ваш рабочий процесс через наш API и инструменты CI/CD.",
      feature3Title: "Интеграция с дизайном",
      feature3Desc: "Идеально подходит для дизайнеров, которые хотят убедиться, что их творения работают для всех, а не только для большинства.",
      feature4Title: "Экспертная поддержка",
      feature4Desc: "Не просто находим проблемы — вы узнаете, как их исправить, благодаря нашим подробным руководствам и практическим рекомендациям.",
      ourValues: "Наши принципы работы",
      value1Title: "Инклюзивность прежде всего",
      value1Desc: "Мы верим, что цифровые продукты должны работать для всех, независимо от способностей. Этим принципом мы руководствуемся в каждом решении.",
      value2Title: "Простота важна",
      value2Desc: "Проверка доступности не должна быть сложной. Мы сделали её настолько простой, что достаточно ввести URL и нажать «проверить».",
      value3Title: "Постоянные улучшения",
      value3Desc: "Веб постоянно развивается, и мы тоже. Мы постоянно улучшаем наши инструменты, чтобы находить последние проблемы доступности.",
      readyToMake: "Готовы улучшить доступность вашего сайта?",
      joinThousands: "Тысячи веб-разработчиков и дизайнеров уже используют ScanWeb для создания доступных и удобных веб-сайтов, соответствующих стандартам WCAG 2.1."
    },
    nav: {
      home: "Главная",
      about: "О нас",
      pricing: "Тарифы",
      resources: "Ресурсы",
      apiDocs: "API документация",
      allTools: "Все инструменты"
    },
    pricing: {
      title: "Простые и прозрачные тарифы",
      subtitle: "Выберите план, который подходит вашим потребностям. Начните бесплатно, обновите в любое время.",
      planFree: "Бесплатно",
      planPro: "Про",
      planEnterprise: "Корпоративный",
      planFreeDesc: "Идеально для начала работы с тестированием доступности",
      planProDesc: "Для профессионалов, которым нужна комплексная проверка доступности",
      planEnterpriseDesc: "Для команд и организаций с расширенными потребностями",
      planForever: "навсегда",
      planPerMonth: "в месяц",
      planCustom: "По запросу",
      planCustomPricing: "цены",
      featureUnlimitedScans: "Неограниченные проверки",
      feature10Scans: "До 10 проверок в месяц",
      featureBasicReport: "Базовый отчёт о доступности",
      featureAdvancedReport: "Расширенные отчёты о доступности",
      featureWCAGAA: "Проверка соответствия WCAG 2.1 AA",
      featureWCAGAAA: "Проверка соответствия WCAG 2.1 AAA",
      featureEmailSupport: "Поддержка по email",
      featurePrioritySupport: "Приоритетная поддержка",
      featureCommunity: "Ресурсы сообщества",
      featurePDFExport: "Экспорт PDF и CSV",
      featureEmailReports: "Отчёты по email",
      featureAPIAccess: "Доступ к API",
      featureCustomIntegrations: "Индивидуальные интеграции",
      featureEverythingPro: "Всё из тарифа Про",
      featureTeamCollab: "Инструменты командной работы",
      featureAnalytics: "Расширенная аналитическая панель",
      featureCustomFrameworks: "Индивидуальные системы соответствия",
      featureAccountManager: "Выделенный менеджер по работе с клиентами",
      featureSLA: "Гарантия SLA",
      featureOnPremise: "Развёртывание на вашей инфраструктуре",
      featureTraining: "Индивидуальные обучающие сессии",
      buttonStartFree: "Начать бесплатно",
      buttonStartPro: "Попробовать Про",
      buttonContactSales: "Связаться с отделом продаж",
      featureFast: "Мгновенная проверка",
      featureFastDesc: "Получите результаты менее чем за 30 секунд",
      featureSecure: "Безопасность и конфиденциальность",
      featureSecureDesc: "Ваши данные зашифрованы и никогда не передаются третьим лицам",
      featureTeam: "Командная работа",
      featureTeamDesc: "Делитесь отчётами и работайте вместе",
      featureSupport: "Экспертная поддержка",
      featureSupportDesc: "Получите помощь, когда она вам нужна",
      mostPopular: "Самый популярный"
    },
    resources: {
      title: "Ресурсы и обучение по доступности",
      subtitle: "Всё, что нужно для освоения веб-доступности",
      categoryAll: "Все",
      categoryBeginner: "Для начинающих",
      categoryAdvanced: "Продвинутый",
      categoryDesign: "Дизайн",
      categoryTesting: "Тестирование",
      categoryDevelopment: "Разработка",
      article1Title: "10 распространённых проблем доступности и способы их решения",
      article1Desc: "Узнайте о самых частых проблемах доступности на сайтах и практических решениях для их устранения.",
      article2Title: "Руководство по соответствию WCAG 2.1: полные стандарты веб-доступности",
      article2Desc: "Освойте Руководство по доступности веб-контента (WCAG) 2.1 для создания инклюзивных, доступных сайтов, соответствующих международным стандартам.",
      article3Title: "Доступность цветового контраста: полное руководство для веб-дизайнеров",
      article3Desc: "Освойте требования к цветовому контрасту для создания доступных, инклюзивных дизайнов, соответствующих стандартам WCAG.",
      article4Title: "Оптимизация для скринридеров: полное руководство по доступности",
      article4Desc: "Узнайте, как оптимизировать сайт для скринридеров и вспомогательных технологий. Создавайте инклюзивный опыт, работающий с NVDA, JAWS, VoiceOver.",
      article5Title: "Доступность навигации с клавиатуры: полное руководство по внедрению",
      article5Desc: "Освойте паттерны навигации с клавиатуры и управление фокусом для создания доступного веб-опыта для пользователей, полагающихся только на клавиатуру.",
      article6Title: "Мобильная доступность: полное руководство по лучшим практикам",
      article6Desc: "Освойте мобильную доступность для создания инклюзивного опыта на смартфонах и планшетах. Изучите основные техники для сенсорных интерфейсов.",
      article7Title: "Создание доступных React-компонентов",
      article7Desc: "Лучшие практики создания доступных React-компонентов, работающих со скринридерами и навигацией с клавиатуры.",
      minRead: "мин чтения",
      comingSoon: "Скоро",
      articlesAndGuides: "Статьи и руководства",
      article: "статья",
      articles: "статей",
      inCategory: "в категории",
      readArticle: "Читать статью →",
      recommendedTools: "Рекомендуемые инструменты",
      toolWebAIM: "WebAIM Contrast Checker",
      toolWebAIMDesc: "Онлайн-инструмент для проверки соотношения цветового контраста",
      toolColorOracle: "Color Oracle",
      toolColorOracleDesc: "Десктопное приложение для симуляции цветовой слепоты",
      toolStark: "Stark Plugin",
      toolStarkDesc: "Плагин для инструментов дизайна для тестирования доступности",
      toolFeatureRealTime: "Расчёт контраста в реальном времени",
      toolFeatureWCAGCheck: "Проверка соответствия WCAG",
      toolFeatureSimulation: "Симуляция цветовой слепоты",
      toolFeaturePreview: "Предпросмотр в реальном времени",
      toolFeatureMultiple: "Множественные типы цветовой слепоты",
      toolFeatureCrossPlatform: "Кросс-платформенная поддержка",
      toolFeatureIntegration: "Интеграция Figma/Sketch",
      toolFeatureScanning: "Проверка контраста",
      visitTool: "Посетить инструмент",
      stayUpdated: "Будьте в курсе",
      stayUpdatedDesc: "Получайте последние советы по доступности, руководства и новости индустрии прямо на вашу почту.",
      subscribeToNewsletter: "Подписаться на рассылку"
    },
    apiDocs: {
      title: "Документация API",
      subtitle: "Интегрируйте сканирование доступности в ваши приложения с помощью нашего мощного REST API.",
      quickStart: "Быстрый старт",
      quickStartDesc: "Начните работу с нашим API за минуты. Всё, что вам нужно — это API-ключ и URL для сканирования.",
      replaceApiKey: "Замените YOUR_API_KEY на ваш фактический API-ключ",
      copy: "Копировать",
      testApi: "Протестировать API",
      testApiDesc: "Попробуйте наш API с реальным URL, чтобы увидеть, как он работает.",
      websiteUrl: "URL сайта",
      success: "Успешно!",
      error: "Ошибка",
      apiEndpoints: "API эндпоинты",
      showDetails: "Показать детали",
      hideDetails: "Скрыть детали",
      parameters: "Параметры",
      required: "Обязательный",
      codeExamples: "Примеры кода",
      authentication: "Аутентификация",
      authDesc: "Все запросы к API требуют аутентификации с использованием API-ключа. Включите ваш API-ключ в заголовок Authorization.",
      getApiKey: "Получите ваш API-ключ из панели управления после регистрации на план Pro или Enterprise.",
      copiedToClipboard: "Скопировано в буфер обмена!",
      endpointScanDesc: "Сканировать сайт на проблемы доступности",
      endpointBatchDesc: "Сканировать несколько URL в одном запросе",
      paramUrl: "URL для сканирования",
      paramDepth: "Глубина сканирования (1-3, по умолчанию: 1)",
      paramInclude: "Список типов проблем через запятую для включения",
      paramUrls: "Массив URL для сканирования",
      paramOptions: "Параметры сканирования для всех URL"
    },
    tools: {
      title: "Инструменты для тестирования доступности",
      subtitle: "Мощные инструменты для проверки и улучшения доступности вашего сайта",
      toolContrast: "Проверка цветового контраста",
      toolContrastDesc: "Проверьте комбинации цветов на соответствие WCAG. Введите hex-коды и получите мгновенные результаты контраста.",
      toolAltText: "Анализатор альтернативного текста",
      toolAltTextDesc: "Просканируйте любую веб-страницу, чтобы найти изображения без атрибутов alt. Идеально для быстрого аудита доступности.",
      toolKeyboard: "Навигация с клавиатуры",
      toolKeyboardDesc: "Протестируйте навигацию с клавиатуры и управление фокусом, чтобы убедиться, что всё работает без мыши.",
      toolPerformance: "Аудит производительности",
      toolPerformanceDesc: "Проанализируйте, как функции доступности влияют на производительность сайта, и оптимизируйте соответственно.",
      toolScreenReader: "Симулятор скринридера",
      toolScreenReaderDesc: "Оцените свой сайт так, как его видят пользователи скринридеров. Протестируйте совместимость с NVDA, JAWS и VoiceOver.",
      statusAvailable: "Доступно",
      featureWCAG: "Соответствие WCAG AA/AAA",
      featureLivePreview: "Живой предпросмотр",
      featureColorGen: "Генератор случайных цветов",
      featureDetailedReport: "Подробный отчёт о соответствии",
      featureBulkScan: "Массовое сканирование изображений",
      featureMissingDetection: "Обнаружение отсутствующего alt-текста",
      featureSuggestions: "Рекомендации по улучшению",
      featureExport: "Экспорт результатов",
      needAdvanced: "Нужны расширенные функции?",
      needAdvancedDesc: "Перейдите на Pro для неограниченных проверок, расширенной отчётности и приоритетной поддержки.",
      viewPricing: "Посмотреть тарифы",
      viewAPI: "Посмотреть API"
    },
    keyboardNavigator: {
      title: "Навигация с клавиатуры",
      subtitle: "Протестируйте и улучшите навигацию с клавиатуры на вашем сайте. Убедитесь, что все интерактивные элементы доступны с клавиатуры, делая ваш сайт удобным для всех, независимо от способа ввода.",
      testTitle: "Тест навигации с клавиатуры",
      testButton: "Тест навигации",
      testing: "Тестирование...",
      whatWeTest: "Что мы проверяем:",
      whatWeTestDesc: "Порядок табуляции, управление фокусом, горячие клавиши, ARIA-метки, индикаторы фокуса и ссылки пропуска.",
      testingInProgress: "Тестирование в процессе...",
      keyboardNavigationIssues: "Проблемы навигации с клавиатуры",
      excellent: "Отлично! Проблем навигации с клавиатуры не найдено.",
      excellentDesc: "Все интерактивные элементы правильно доступны с клавиатуры.",
      bestPracticesTitle: "Лучшие практики навигации с клавиатуры",
      essentialRequirements: "Основные требования",
      advancedFeatures: "Расширенные функции",
      needMoreTools: "Нужны дополнительные инструменты доступности?",
      needMoreToolsDesc: "Изучите наш полный набор инструментов для тестирования доступности.",
      viewAllTools: "Посмотреть все инструменты",
      errorEnterUrl: "Пожалуйста, введите URL для тестирования",
      essentialItem1: "Тестируйте навигацию Tab через все интерактивные элементы",
      essentialItem2: "Проверяйте, что логический порядок табуляции соответствует визуальной компоновке",
      essentialItem3: "Убедитесь, что индикаторы фокуса четко видны",
      essentialItem4: "Проверяйте, что клавиша Escape закрывает все модальные окна и выпадающие меню",
      essentialItem5: "Тестируйте ссылки пропуска для обхода повторяющейся навигации",
      essentialItem6: "Проверяйте работу стрелочных клавиш в пользовательских компонентах",
      essentialItem7: "Тестируйте, что горячие клавиши не конфликтуют с настройками браузера по умолчанию",
      advancedItem1: "Тестируйте пользовательские горячие клавиши (Ctrl+S, Alt+N и т.д.)",
      advancedItem2: "Проверяйте навигацию стрелочными клавишами в выпадающих меню",
      advancedItem3: "Тестируйте захват фокуса в модальных диалогах",
      advancedItem4: "Проверяйте восстановление фокуса после закрытия модальных окон",
      advancedItem5: "Тестируйте навигацию с клавиатуры в одностраничных приложениях",
      advancedItem6: "Проверяйте управление фокусом при динамических обновлениях контента",
      advancedItem7: "Тестируйте навигацию с клавиатуры со скринридерами",
      issuesFound: "Найдено проблем",
      navigationScore: "Оценка навигации"
    },
    performanceAudit: {
      title: "Аудит производительности",
      subtitle: "Проанализируйте производительность вашего сайта и получите практические рекомендации для улучшения скорости загрузки и пользовательского опыта. Создавайте молниеносные сайты, которые нравятся пользователям.",
      auditTitle: "Аудит производительности сайта",
      startAudit: "Начать аудит",
      auditing: "Аудит...",
      errorEnterUrl: "Пожалуйста, введите URL для аудита",
      errorAuditFailed: "Ошибка при аудите производительности. Пожалуйста, попробуйте снова.",
      whatWeAnalyze: "Что мы анализируем:",
      whatWeAnalyzeDesc: "Core Web Vitals, производительность загрузки, оптимизация ресурсов, стратегии кэширования и влияние доступности на производительность.",
      performanceScore: "Оценка производительности",
      excellent: "Отличная производительность!",
      good: "Хорошая производительность с возможностью улучшения",
      needsImprovement: "Производительность требует значительного улучшения",
      coreWebVitals: "Core Web Vitals",
      performanceIssues: "Проблемы производительности",
      quickRecommendations: "Быстрые рекомендации",
      bestPracticesTitle: "Лучшие практики производительности",
      coreOptimizations: "Основные оптимизации",
      advancedTechniques: "Продвинутые техники",
      needMoreTools: "Нужны дополнительные инструменты производительности?",
      needMoreToolsDesc: "Изучите наш полный набор инструментов для тестирования производительности и доступности.",
      coreItem1: "Тестируйте скорость загрузки страницы и Core Web Vitals",
      coreItem2: "Анализируйте оптимизацию изображений и использование форматов",
      coreItem3: "Проверяйте размер JavaScript-бандла и производительность загрузки",
      coreItem4: "Проверяйте оптимизацию CSS и критический путь",
      coreItem5: "Тестируйте производительность на мобильных устройствах и адаптивную загрузку",
      coreItem6: "Проверяйте время отклика сервера и заголовки кэширования",
      coreItem7: "Анализируйте влияние сторонних скриптов на производительность",
      advancedItem1: "Тестируйте разделение кода и динамические импорты",
      advancedItem2: "Анализируйте реализацию service worker и кэширование",
      advancedItem3: "Проверяйте извлечение и встраивание критического CSS",
      advancedItem4: "Тестируйте подсказки ресурсов (preload, prefetch, preconnect)",
      advancedItem5: "Проверяйте оптимизацию HTTP/2 и HTTP/3",
      advancedItem6: "Тестируйте функции производительности прогрессивных веб-приложений",
      advancedItem7: "Анализируйте бюджеты производительности и мониторинг",
      performanceScore: "Оценка производительности",
      excellentPerformance: "Отличная производительность!",
      goodPerformance: "Хорошая производительность с возможностью улучшения",
      needsImprovement: "Производительность требует значительного улучшения"
    },
    screenReaderSimulator: {
      title: "Симулятор скринридера",
      subtitle: "Оцените свой сайт так, как его видят пользователи скринридеров. Протестируйте доступность и улучшите опыт для всех пользователей, обеспечив действительно инклюзивный и доступный контент.",
      simulateTitle: "Симуляция опыта скринридера",
      startSimulation: "Начать симуляцию",
      simulating: "Симуляция...",
      errorEnterUrl: "Пожалуйста, введите URL для симуляции",
      errorSimulationFailed: "Ошибка при симуляции скринридера. Пожалуйста, попробуйте снова.",
      whatWeSimulate: "Что мы симулируем:",
      whatWeSimulateDesc: "Навигацию скринридера, ARIA-объявления, структуру заголовков, метки форм и идентификацию ориентиров.",
      accessibilityScore: "Оценка доступности",
      accessibleElements: "Доступные элементы",
      issuesFound: "Найдено проблем",
      totalElements: "Всего элементов",
      screenReaderOutput: "Вывод скринридера",
      issuesFoundTab: "Найденные проблемы",
      recommendationsTab: "Рекомендации",
      accessibilityIssues: "Проблемы доступности",
      bestPracticesTitle: "Лучшие практики скринридера",
      essentialRequirements: "Основные требования",
      advancedFeatures: "Расширенные функции",
      needMoreTools: "Нужны дополнительные инструменты доступности?",
      needMoreToolsDesc: "Изучите наш полный набор инструментов для тестирования и симуляции доступности.",
      essentialItem1: "Тестируйте, как скринридеры объявляют содержимое страницы",
      essentialItem2: "Проверяйте, что alt-текст описателен и значим",
      essentialItem3: "Проверяйте иерархию заголовков и структуру документа",
      essentialItem4: "Тестируйте метки форм и объявления об ошибках",
      essentialItem5: "Проверяйте, что ARIA-метки и описания объявляются",
      essentialItem6: "Тестируйте навигацию по ориентирам и областям страницы",
      essentialItem7: "Проверяйте живые области для динамических обновлений контента",
      advancedItem1: "Тестируйте живые области для обновлений контента в реальном времени",
      advancedItem2: "Проверяйте управление фокусом в модальных диалогах",
      advancedItem3: "Тестируйте ссылки пропуска и навигацию по ориентирам",
      advancedItem4: "Проверяйте описательный текст ссылок и контекст",
      advancedItem5: "Тестируйте с несколькими программами скринридеров",
      advancedItem6: "Проверяйте ARIA-объявления и изменения состояния",
      advancedItem7: "Тестируйте сложные взаимодействия и пользовательские компоненты",
      accessibilityScore: "Оценка доступности",
      accessibleElements: "Доступные элементы",
      totalElements: "Всего элементов"
    },
    altTextAnalyzer: {
      title: "Анализатор альтернативного текста",
      subtitle: "Проанализируйте и улучшите альтернативный текст для изображений на вашем сайте, чтобы обеспечить доступность для скринридеров. Сделайте ваш визуальный контент доступным для всех.",
      analyzeTitle: "Анализ изображений сайта",
      analyzeDesc: "Введите URL сайта для анализа всех изображений на правильную реализацию альтернативного текста.",
      analyzeImages: "Анализировать изображения",
      analyzing: "Анализ...",
      successMessage: "Анализ альтернативного текста успешно завершён",
      errorAnalyzeFailed: "Ошибка при анализе изображений. Пожалуйста, попробуйте снова.",
      websiteUrl: "URL сайта",
      totalImages: "Всего изображений",
      withAltText: "С альтернативным текстом",
      missingAlt: "Отсутствует alt",
      emptyAlt: "Пустой alt",
      issuesFound: "Найдено проблем",
      bestPracticesTitle: "Лучшие практики альтернативного текста",
      dos: "Рекомендации",
      donts: "Не рекомендуется",
      do1: "Тестируйте alt-текст со скринридерами",
      do1Desc: "Проверьте, как звучит alt-текст при чтении вспомогательными технологиями",
      do2: "Проверяйте отсутствующие атрибуты alt",
      do2Desc: "Просканируйте все изображения, чтобы убедиться, что у них есть правильный alt-текст или пустой атрибут alt",
      do3: "Убедитесь, что декоративные изображения имеют alt=''",
      do3Desc: "Декоративные изображения должны иметь пустой alt-текст, чтобы скринридеры их пропускали",
      do4: "Проверяйте длину и ясность alt-текста",
      do4Desc: "Убедитесь, что alt-текст краток, но достаточно описателен, чтобы передать смысл",
      dont1: "Игнорируйте изображения без атрибутов alt",
      dont1Desc: "Отсутствие alt-текста делает изображения полностью недоступными для пользователей скринридеров",
      dont2: "Используйте placeholder или общий alt-текст",
      dont2Desc: "Текст типа 'изображение' или 'фото' не предоставляет значимой информации",
      dont3: "Пропускайте тестирование с реальными скринридерами",
      dont3Desc: "Всегда проверяйте, как звучит alt-текст при чтении вспомогательными технологиями",
      dont4: "Забывайте тестировать разные типы изображений",
      dont4Desc: "Тестируйте декоративные, информативные и функциональные изображения по-разному"
    },
    colorContrastChecker: {
      title: "Проверка цветового контраста",
      subtitle: "Проверьте комбинации цветов, чтобы убедиться, что они соответствуют стандартам доступности WCAG.",
      chooseColors: "Выберите цвета",
      foregroundColor: "Цвет текста",
      backgroundColor: "Цвет фона",
      randomizeColors: "Случайные цвета",
      preview: "Предпросмотр",
      sampleText: "Пример текста",
      previewDescription: "Так будет выглядеть ваш текст с этими цветами.",
      contrastAnalysis: "Анализ контраста",
      contrastRatio: "Соотношение контраста",
      wcagAA: "WCAG AA",
      wcagAAA: "WCAG AAA",
      wcagAALarge: "WCAG AA Крупный",
      pass: "ПРОЙДЕНО",
      fail: "НЕ ПРОЙДЕНО",
      normalText: "Обычный текст",
      largeText: "Крупный текст"
    },
    index: {
      statsScanned: "Сайтов проверено",
      statsAccuracy: "Точность",
      statsFixed: "Проблем исправлено",
      statsCompliance: "Соответствие",
      whyChoose: "Почему выбирают наш сканер доступности?",
      featureAnalysis: "Комплексный анализ",
      featureAnalysisDesc: "Продвинутое AI-сканирование обнаруживает 50+ проблем доступности, включая цветовой контраст, alt-текст, навигацию с клавиатуры, ARIA-метки и совместимость со скринридерами с точностью 99,9%.",
      featureFast: "Мгновенные результаты",
      featureFastDesc: "Получите подробные отчёты о доступности менее чем за 30 секунд с практическими рекомендациями, фрагментами кода и категоризацией проблем по приоритетам для немедленной реализации.",
      featureWCAG: "Соответствие WCAG 2.1 AA",
      featureWCAGDesc: "Обеспечивает соответствие вашего сайта международным стандартам доступности (WCAG 2.1 AA) и правовым требованиям, включая ADA, Section 508 и EN 301 549.",
      featureReports: "Профессиональные отчёты",
      featureReportsDesc: "Генерируйте подробные PDF-отчёты с резюме, детальными находками, руководствами по исправлению и отслеживанием прогресса для презентаций стейкхолдерам и документации соответствия.",
      featureSecurity: "Корпоративная безопасность",
      featureSecurityDesc: "Банковый уровень безопасности с соответствием SOC 2, шифрованием передачи данных и подходом, ориентированным на конфиденциальность. Данные вашего сайта никогда не хранятся и не передаются третьим лицам.",
      featureExpert: "Экспертная поддержка",
      featureExpertDesc: "Круглосуточная техническая поддержка от экспертов по доступности, помощь в интеграции, индивидуальные правила сканирования и постоянные консультации для успеха вашей цифровой доступности.",
      tooltipClear: "Очистить все результаты сканирования и начать заново",
      ariaUrlLabel: "URL сайта для проверки на проблемы доступности",
      trustedBy: "Нам доверяют ведущие организации по всему миру",
      orgFortune500: "Компании из списка Fortune 500",
      orgGovernment: "Государственные агентства",
      orgEducational: "Образовательные учреждения",
      orgHealthcare: "Медицинские организации",
      orgEcommerce: "Электронные торговые платформы",
      orgFinancial: "Финансовые услуги",
      technicalSpecs: "Технические характеристики",
      specScanningTech: "Технология сканирования",
      specCompliance: "Стандарты соответствия",
      specIntegration: "Варианты интеграции",
      detailAIAnalysis: "Анализ на основе ИИ",
      detailRealTime: "Обработка в реальном времени",
      detail50Checks: "50+ типов проверок",
      detailCustomRules: "Механизм пользовательских правил",
      detailWCAG: "WCAG 2.1 AA/AAA",
      detailADA: "Соответствие ADA",
      detailSection508: "Section 508",
      detailEN301549: "EN 301 549",
      detailRESTAPI: "REST API",
      detailWebhook: "Поддержка Webhook",
      detailCICD: "Интеграция CI/CD",
      detailBrowserExt: "Расширение браузера",
      detailedReportsTitle: "Подробные отчёты с практическими рекомендациями",
      detailedReportsDesc: "Наш продвинутый сканер проверяет ваш сайт на соответствие стандартам WCAG и предоставляет подробные отчёты с практическими рекомендациями.",
      reportWCAGTitle: "Соответствие WCAG",
      reportWCAGDesc: "Комплексное тестирование на соответствие Руководству по доступности веб-контента 2.1 AA.",
      reportDetailedTitle: "Подробные отчёты",
      reportDetailedDesc: "Получите конкретные рекомендации по каждой проблеме доступности, найденной на вашем сайте.",
      reportExportTitle: "Экспорт и обмен",
      reportExportDesc: "Скачайте PDF-отчёты или отправьте результаты по email своей команде для совместной работы."
    }
  }
};

export const LanguageProvider = ({ children }) => {
  // Initialize with default language, will be updated on client
  const [language, setLanguage] = useState('en');
  const [isClient, setIsClient] = useState(false);

  // Load language preference from localStorage on mount (client-side only)
  useEffect(() => {
    // Set isClient to true immediately when component mounts on client
    setIsClient(true);
    
    // Check for saved language or browser language
    if (typeof window !== 'undefined' && typeof localStorage !== 'undefined') {
      try {
        const savedLanguage = localStorage.getItem('language');
        if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ru')) {
          setLanguage(savedLanguage);
        } else if (typeof navigator !== 'undefined') {
          // Check browser language
          const browserLang = navigator.language || navigator.userLanguage;
          if (browserLang && browserLang.startsWith('ru')) {
            setLanguage('ru');
          }
        }
      } catch (e) {
        // localStorage might not be available
        console.warn('Could not access localStorage:', e);
      }
    }
  }, []);

  // Save language preference to localStorage and update document
  useEffect(() => {
    if (isClient && typeof window !== 'undefined' && typeof localStorage !== 'undefined') {
      try {
        localStorage.setItem('language', language);
        // Update document lang attribute
        if (typeof document !== 'undefined') {
          document.documentElement.lang = language;
        }
      } catch (e) {
        console.warn('Could not save language preference:', e);
      }
    }
  }, [language, isClient]);

  const changeLanguage = (lang) => {
    if (lang === 'en' || lang === 'ru') {
      setLanguage(lang);
    }
  };

  const t = (path) => {
    const keys = path.split('.');
    let value = translations[language];
    
    for (const key of keys) {
      if (value && typeof value === 'object') {
        value = value[key];
      } else {
        return path; // Return path if translation not found
      }
    }
    
    return value || path;
  };

  const value = {
    language,
    changeLanguage,
    t,
    isClient
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

